const elements={lock:document.querySelector("#lock"),standards:document.querySelector("#standards"),form:document.querySelector("#unlock-form"),password:document.querySelector("#password"),toggle:document.querySelector("#toggle-password"),status:document.querySelector("#unlock-status"),search:document.querySelector("#search"),view:document.querySelector("#view"),container:document.querySelector("#table-container"),count:document.querySelector("#result-count"),lockAgain:document.querySelector("#lock-again")};
let records=[];
const decode=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
async function decrypt(password){const response=await fetch("standards.enc.json",{cache:"no-store"});if(!response.ok)throw new Error("Daten nicht verfügbar");const payload=await response.json();const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveKey"]);const key=await crypto.subtle.deriveKey({name:"PBKDF2",salt:decode(payload.salt),iterations:payload.iterations,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,["decrypt"]);const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(payload.iv)},key,decode(payload.ciphertext));return JSON.parse(new TextDecoder().decode(plaintext)).records}
function cell(text,tag="td"){const el=document.createElement(tag);el.textContent=text||"";return el}
function tableFor(rows,columns){const table=document.createElement("table"),head=document.createElement("thead"),headRow=document.createElement("tr"),body=document.createElement("tbody");columns.forEach(column=>headRow.append(cell(column.label,"th")));head.append(headRow);rows.forEach(row=>{const tr=document.createElement("tr");columns.forEach(column=>tr.append(cell(row[column.key])));body.append(tr)});table.append(head,body);return table}
function render(){const query=elements.search.value.trim().toLocaleLowerCase("de"),filtered=query?records.filter(row=>Object.values(row).some(value=>String(value).toLocaleLowerCase("de").includes(query))):records;elements.count.textContent=`${filtered.length} von ${records.length} Standards`;elements.container.replaceChildren();if(elements.view.value==="medication"){elements.container.append(tableFor([...filtered].sort((a,b)=>a.Medikation.localeCompare(b.Medikation,"de")),[{key:"Medikation",label:"Medikation"},{key:"Kategorie / Situation",label:"Kategorie"},{key:"KMT-Std.",label:"KMT-Standard"}]));return}const groups=Map.groupBy?Map.groupBy(filtered,row=>row["Kategorie / Situation"]||"Unkategorisiert"):filtered.reduce((map,row)=>{const key=row["Kategorie / Situation"]||"Unkategorisiert";map.set(key,[...(map.get(key)||[]),row]);return map},new Map());[...groups.keys()].sort((a,b)=>a.localeCompare(b,"de")).forEach(category=>{const details=document.createElement("details"),summary=document.createElement("summary");summary.textContent=category;const badge=document.createElement("span");badge.textContent=groups.get(category).length;summary.append(badge);details.append(summary,tableFor(groups.get(category),[{key:"Medikation",label:"Medikation"},{key:"KMT-Std.",label:"KMT-Standard"}]));elements.container.append(details)})}
elements.form.addEventListener("submit",async event=>{event.preventDefault();elements.status.textContent="Standards werden entschlüsselt …";try{records=await decrypt(elements.password.value);elements.password.value="";elements.lock.hidden=true;elements.standards.hidden=false;elements.status.textContent="";render();elements.search.focus()}catch(error){elements.status.textContent="Passwort nicht korrekt oder Daten nicht verfügbar.";elements.password.select()}});
elements.toggle.addEventListener("click",()=>{const visible=elements.password.type==="text";elements.password.type=visible?"password":"text";elements.toggle.textContent=visible?"Anzeigen":"Ausblenden"});
elements.search.addEventListener("input",render);elements.view.addEventListener("change",render);elements.lockAgain.addEventListener("click",()=>{records=[];elements.container.replaceChildren();elements.standards.hidden=true;elements.lock.hidden=false;elements.password.focus()});
