const $=selector=>document.querySelector(selector);
const elements={lock:$("#lock"),standards:$("#standards"),form:$("#unlock-form"),password:$("#password"),rememberDevice:$("#remember-device"),toggle:$("#toggle-password"),status:$("#unlock-status"),search:$("#search"),view:$("#view"),container:$("#table-container"),count:$("#result-count"),lockAgain:$("#lock-again"),forgetDevice:$("#forget-device"),openAdmin:$("#open-admin"),adminDialog:$("#admin-dialog"),adminForm:$("#admin-form"),adminPassword:$("#admin-password"),adminStatus:$("#admin-status"),closeAdmin:$("#close-admin"),toggleAdmin:$("#toggle-admin-password"),editor:$("#editor"),editorContainer:$("#editor-container"),editorStatus:$("#editor-status"),editorSearch:$("#editor-search"),editorSort:$("#editor-sort"),closeEditor:$("#close-editor"),csvImport:$("#csv-import"),addRecord:$("#add-record"),exportEncrypted:$("#export-encrypted"),controls:$(".controls")};
let records=[],dataKey,dataMeta;
const fields=["Medikation","Kategorie / Situation","KMT-Std."];
const accessDuration=7*24*60*60*1000,accessDatabase="kmt-standards-access",accessStore="remembered-access";
const decode=value=>Uint8Array.from(atob(value),char=>char.charCodeAt(0));
const encode=value=>btoa(String.fromCharCode(...new Uint8Array(value)));
const equal=(a,b)=>a.length===b.length&&a.reduce((difference,value,index)=>difference|(value^b[index]),0)===0;

async function deriveKey(password,salt,iterations,usages){const material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveKey","deriveBits"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations,hash:"SHA-256"},material,{name:"AES-GCM",length:256},false,usages)}
async function fetchPayload(){const response=await fetch("standards.enc.json",{cache:"no-store"});if(!response.ok)throw new Error("Daten nicht verfügbar");return response.json()}
async function decryptWithKey(payload,key){const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:decode(payload.iv)},key,decode(payload.ciphertext));return{records:JSON.parse(new TextDecoder().decode(plaintext)).records,key,meta:{salt:payload.salt,iterations:payload.iterations}}}
async function decrypt(password){const payload=await fetchPayload(),key=await deriveKey(password,decode(payload.salt),payload.iterations,["encrypt","decrypt"]);return decryptWithKey(payload,key)}
function accessDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(accessDatabase,1);request.onupgradeneeded=()=>request.result.createObjectStore(accessStore,{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function accessRecord(mode,value){const database=await accessDb();return new Promise((resolve,reject)=>{const transaction=database.transaction(accessStore,mode),store=transaction.objectStore(accessStore),request=value===undefined?store.get("reader"):value===null?store.delete("reader"):store.put(value);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);transaction.oncomplete=()=>database.close()})}
async function rememberAccess(key,meta){await accessRecord("readwrite",{id:"reader",key,salt:meta.salt,iterations:meta.iterations,expiresAt:Date.now()+accessDuration});elements.forgetDevice.hidden=false}
async function forgetAccess(){try{await accessRecord("readwrite",null)}catch{}elements.forgetDevice.hidden=true}
function showStandards(result,remembered=false){records=result.records;dataKey=result.key;dataMeta=result.meta;elements.password.value="";elements.lock.hidden=true;elements.standards.hidden=false;elements.status.textContent="";elements.forgetDevice.hidden=!remembered;render();elements.search.focus()}
async function restoreRememberedAccess(){try{const saved=await accessRecord("readonly");if(!saved)return;if(saved.expiresAt<=Date.now()){await forgetAccess();return}elements.status.textContent="Gespeicherter Zugang wird geprüft …";const payload=await fetchPayload();if(saved.salt!==payload.salt||saved.iterations!==payload.iterations)throw new Error("Zugang veraltet");showStandards(await decryptWithKey(payload,saved.key),true)}catch{await forgetAccess();elements.status.textContent="Der gespeicherte Zugang ist nicht mehr gültig. Bitte Passwort eingeben."}}
async function verifyAdmin(password){const response=await fetch("admin.config.json",{cache:"no-store"});if(!response.ok)return false;const config=await response.json(),material=await crypto.subtle.importKey("raw",new TextEncoder().encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:decode(config.salt),iterations:config.iterations,hash:"SHA-256"},material,256);return equal(new Uint8Array(bits),decode(config.verifier))}
function cell(text,tag="td"){const element=document.createElement(tag);element.textContent=text||"";return element}
function tableFor(rows,columns){const table=document.createElement("table"),head=document.createElement("thead"),headRow=document.createElement("tr"),body=document.createElement("tbody");columns.forEach(column=>headRow.append(cell(column.label,"th")));head.append(headRow);rows.forEach(row=>{const tr=document.createElement("tr");columns.forEach(column=>tr.append(cell(row[column.key])));body.append(tr)});table.append(head,body);return table}
function render(){const query=elements.search.value.trim().toLocaleLowerCase("de"),filtered=query?records.filter(row=>Object.values(row).some(value=>String(value).toLocaleLowerCase("de").includes(query))):records;elements.count.textContent=`${filtered.length} von ${records.length} Standards`;elements.container.replaceChildren();if(elements.view.value==="medication"){elements.container.append(tableFor([...filtered].sort((a,b)=>a.Medikation.localeCompare(b.Medikation,"de")),[{key:"Medikation",label:"Medikation"},{key:"Kategorie / Situation",label:"Kategorie"},{key:"KMT-Std.",label:"KMT-Standard"}]));return}const groups=filtered.reduce((map,row)=>{const key=row["Kategorie / Situation"]||"Unkategorisiert";map.set(key,[...(map.get(key)||[]),row]);return map},new Map());[...groups.keys()].sort((a,b)=>a.localeCompare(b,"de")).forEach(category=>{const details=document.createElement("details"),summary=document.createElement("summary");summary.textContent=category;const badge=document.createElement("span");badge.textContent=groups.get(category).length;summary.append(badge);details.append(summary,tableFor(groups.get(category),[{key:"Medikation",label:"Medikation"},{key:"KMT-Std.",label:"KMT-Standard"}]));elements.container.append(details)})}
function renderEditor(){const query=elements.editorSearch.value.trim().toLocaleLowerCase("de"),compare=(a,b,field,second)=>String(a.record[field]||"").localeCompare(String(b.record[field]||""),"de")||String(a.record[second]||"").localeCompare(String(b.record[second]||""),"de"),entries=records.map((record,index)=>({record,index})).filter(({record})=>!query||[record.Medikation,record["Kategorie / Situation"]].some(value=>String(value||"").toLocaleLowerCase("de").includes(query)));entries.sort(elements.editorSort.value==="medication"?(a,b)=>compare(a,b,"Medikation","Kategorie / Situation"):(a,b)=>compare(a,b,"Kategorie / Situation","Medikation"));elements.editorContainer.replaceChildren();const table=document.createElement("table"),head=document.createElement("thead"),headRow=document.createElement("tr"),body=document.createElement("tbody");[...fields,""].forEach(label=>headRow.append(cell(label,"th")));head.append(headRow);entries.forEach(({record,index})=>{const row=document.createElement("tr");row.dataset.recordIndex=index;fields.forEach(field=>{const td=document.createElement("td"),input=document.createElement(field==="KMT-Std."?"textarea":"input");input.value=record[field]||"";input.setAttribute("aria-label",`${field}, Eintrag ${index+1}`);input.addEventListener("input",()=>{records[index][field]=input.value});td.append(input);row.append(td)});const action=document.createElement("td"),remove=document.createElement("button");remove.type="button";remove.className="delete-row";remove.textContent="Löschen";remove.addEventListener("click",()=>{records.splice(index,1);renderEditor()});action.append(remove);row.append(action);body.append(row)});table.append(head,body);elements.editorContainer.append(table);elements.editorStatus.textContent=`${entries.length} von ${records.length} Standards in Bearbeitung.`}
function parseCsv(text){const rows=[];let row=[],field="",quoted=false;for(let index=0;index<text.length;index++){const char=text[index];if(char==='"'){if(quoted&&text[index+1]==='"'){field+='"';index++}else quoted=!quoted}else if(char===";"&&!quoted){row.push(field);field=""}else if((char==="\n"||char==="\r")&&!quoted){if(char==="\r"&&text[index+1]==="\n")index++;row.push(field);field="";if(row.some(value=>value.trim()))rows.push(row);row=[]}else field+=char}if(field||row.length){row.push(field);rows.push(row)}const headers=rows.shift().map(value=>value.replace(/^\uFEFF/,"").trim());if(!fields.every(fieldName=>headers.includes(fieldName)))throw new Error("Die CSV enthält nicht die erwarteten Spalten.");return rows.map(values=>Object.fromEntries(headers.map((header,index)=>[header,(values[index]||"").trim()]))) }
async function exportEncrypted(){const iv=crypto.getRandomValues(new Uint8Array(12)),plaintext=new TextEncoder().encode(JSON.stringify({version:1,records})),ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv},dataKey,plaintext),payload={version:1,kdf:"PBKDF2-SHA-256",iterations:dataMeta.iterations,salt:dataMeta.salt,iv:encode(iv),ciphertext:encode(ciphertext)},blob=new Blob([JSON.stringify(payload)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="standards.enc.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);elements.editorStatus.textContent="Verschlüsselte Aktualisierung wurde erstellt. Ersetze damit die gleichnamige Datei bei GitHub."}

elements.form.addEventListener("submit",async event=>{event.preventDefault();elements.status.textContent="Standards werden entschlüsselt …";try{const result=await decrypt(elements.password.value);let remembered=false;if(elements.rememberDevice.checked){try{await rememberAccess(result.key,result.meta);remembered=true}catch{}}else await forgetAccess();elements.rememberDevice.checked=false;showStandards(result,remembered)}catch{elements.status.textContent="Passwort nicht korrekt oder Daten nicht verfügbar.";elements.password.select()}});
elements.toggle.addEventListener("click",()=>{const visible=elements.password.type==="text";elements.password.type=visible?"password":"text";elements.toggle.textContent=visible?"Anzeigen":"Ausblenden"});
elements.openAdmin.addEventListener("click",()=>{elements.adminStatus.textContent="";elements.adminPassword.value="";elements.adminDialog.showModal();elements.adminPassword.focus()});
elements.adminForm.addEventListener("submit",async event=>{event.preventDefault();elements.adminStatus.textContent="Administratorpasswort wird geprüft …";if(await verifyAdmin(elements.adminPassword.value)){elements.adminPassword.value="";elements.adminDialog.close();elements.controls.hidden=true;elements.count.hidden=true;elements.container.hidden=true;elements.editor.hidden=false;renderEditor()}else{elements.adminStatus.textContent="Administratorpasswort nicht korrekt.";elements.adminPassword.select()}});
elements.closeAdmin.addEventListener("click",()=>elements.adminDialog.close());elements.toggleAdmin.addEventListener("click",()=>{const visible=elements.adminPassword.type==="text";elements.adminPassword.type=visible?"password":"text";elements.toggleAdmin.textContent=visible?"Anzeigen":"Ausblenden"});
elements.closeEditor.addEventListener("click",()=>{elements.editor.hidden=true;elements.controls.hidden=false;elements.count.hidden=false;elements.container.hidden=false;render()});
elements.csvImport.addEventListener("change",async()=>{const file=elements.csvImport.files[0];if(!file)return;try{records=parseCsv(await file.text());elements.editorSearch.value="";renderEditor();elements.editorStatus.textContent=`${records.length} Standards wurden aus der CSV importiert.`}catch(error){elements.editorStatus.textContent=error.message}finally{elements.csvImport.value=""}});
elements.addRecord.addEventListener("click",()=>{const index=records.length;records.push(Object.fromEntries(fields.map(field=>[field,""])));elements.editorSearch.value="";renderEditor();elements.editorContainer.querySelector(`tr[data-record-index="${index}"] input`)?.focus()});elements.exportEncrypted.addEventListener("click",exportEncrypted);
elements.editorSearch.addEventListener("input",renderEditor);elements.editorSort.addEventListener("change",renderEditor);
elements.search.addEventListener("input",render);elements.view.addEventListener("change",render);elements.forgetDevice.addEventListener("click",async()=>{await forgetAccess();elements.forgetDevice.hidden=true});elements.lockAgain.addEventListener("click",()=>{records=[];dataKey=undefined;dataMeta=undefined;elements.container.replaceChildren();elements.editor.hidden=true;elements.controls.hidden=false;elements.count.hidden=false;elements.container.hidden=false;elements.standards.hidden=true;elements.lock.hidden=false;elements.password.focus()});
restoreRememberedAccess();
